import { PrismaClient } from "@prisma/client";

export const prisma = new PrismaClient();

// EVIL! PUT THE DB BACK!!!!
// oh my goodness u realy destoyed the sqlite

export const fakeShitJob = [
  {
    id: 1,
    name: "Ivoine Cafe",
    address: "x: 34, z: 90, on the mc server",
    description: "not number 1 cafe",
    imgUrl: "1.jpg",
    quiet: 1,
    wifi: 6,
    outlets: 10,
    coffee: 3,
    tea: 5,
  },
  {
    id: 2,
    name: "Adithya Cafe",
    address: "next to the one piece",
    description: "not number 1 cafe",
    imgUrl: "2.jpg",
    quiet: 6,
    wifi: 2,
    outlets: 7,
    coffee: 1,
    tea: 4,
  },
  {
    id: 3,
    name: "Emily Cafe",
    address: "cant rember 💀",
    description: "not number 1 cafe",
    imgUrl: "3.jpg",
    quiet: 1,
    wifi: 7,
    outlets: 3,
    coffee: 8,
    tea: 2,
  },
  {
    id: 4,
    name: "Sahana Cafe",
    address: "in the ocean",
    description: "not number 1 cafe",
    imgUrl: "4.jpg",
    quiet: 5,
    wifi: 2,
    outlets: 8,
    coffee: 4,
    tea: 9,
  },
  {
    id: 5,
    name: "Vidit Cafe",
    address: "across the street",
    description: "not number 1 cafe",
    imgUrl: "5.jpg",
    quiet: 8,
    wifi: 6,
    outlets: 3,
    coffee: 9,
    tea: 5,
  },
  {
    id: 6,
    name: "Kaiwen Cafe",
    address: "idk",
    description: "not number 1 cafe",
    imgUrl: "6.jpg",
    quiet: 9,
    wifi: 10,
    outlets: 7,
    coffee: 4,
    tea: 10,
  },
  {
    id: 7,
    name: "Marc Cafe",
    address: "somewhere in ikea",
    description: "number 1 cafe",
    imgUrl: "7.jpg",
    quiet: 999999,
    wifi: 99999,
    outlets: 9999,
    coffee: 99999,
    tea: 999999,
  },
  {
    id: 8,
    name: "Alex Cafe",
    address: "alex location",
    description: "not number 1 cafe",
    imgUrl: "8.jpg",
    quiet: 1,
    wifi: 4,
    outlets: 7,
    coffee: 10,
    tea: 2,
  },
  {
    id: 9,
    name: "Kevin Cafe",
    address: "kevin home",
    description: "not number 1 cafe",
    imgUrl: "9.jpg",
    quiet: 0,
    wifi: 0, // all 0 beause u took my db ;(
    outlets: 0,
    coffee: 0,
    tea: 0,
  },
  {
    id: 10,
    name: "Amy Cafe",
    address: "amy house",
    description: "not number 1 cafe",
    imgUrl: "10.jpg",
    quiet: 5,
    wifi: 4,
    outlets: 3,
    coffee: 6,
    tea: 9,
  },
];
