import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ReactElement } from "react";
import Navbar from "../components/Navbar";
import home from "../public/images/home.png";
import styles from "../styles/Home.module.scss";

export default function Home(): ReactElement {
  return (
    <div id={styles.content}>
      <Head>
        <title>Remotely</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="px-10 sm:px-16 py-8">
        <header className="pt-12 sm:pt-24">
          <h1 className="pb-2 font-bold text-5xl" style={{ color: "#66A473" }}>
            Find your ideal
          </h1>
          <h1 className="font-bold text-5xl" style={{ color: "#66A473" }}>
            curated space
          </h1>
        </header>
        <div className="pt-6 max-w-lg lg:max-w-xl">
          <p className="text-2xl">
            Whether you’re a team of one, a growing startup, or a Fortune 500
            company—we have solutions for all the ways you work.
          </p>
        </div>
        <div className="pt-6">
          <p className="text-xl">Find Workspace In</p>
          <select className="text-xl px-2 py-2 border border-black rounded-md">
            <option>SF Bay Area</option>
          </select>
        </div>
      </div>
      <div className="xl:hidden">
        <Image src={home} width="100%" height="100%" layout="responsive" />
      </div>
    </div>
  );
}
