import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import home from "../public/images/home.png";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div id={styles.content}>
      <Head>
        <title>Remotely</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="px-10 sm:px-16 py-8">
        <header className="pt-12 sm:pt-24">
          <h1 className="pb-2 font-bold text-5xl" style={{ color: "#66A473" }}>
            Find your ideal
          </h1>
          <h1 className="font-bold text-5xl" style={{ color: "#66A473" }}>
            curated space
          </h1>
        </header>
        <div className="pt-6 max-w-lg lg:max-w-xl">
          <p className="text-2xl">
            Filter, bullet-points, verified lorum ipsum placeholder text
            placeholder text placeholder text placeholder text text.
          </p>
        </div>
        <div className="pt-6">
          <p>Find Workspace In</p>
          <select>
            <option>Got too lazy to style this</option>
          </select>
        </div>
      </div>
      <div className="xl:hidden">
        <Image src={home} width="100%" height="100%" layout="responsive" />
      </div>
    </div>
  );
};

export default Home;
