import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";

const Signup: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Remotely</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <p>Hello! We’re happy to see you here.</p>
      <p>Create Account</p>
      <a href="/login">Already a member? Log in</a>
    </div>
  );
};

export default Signup;
